//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLaptop.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanPham", Namespace="http://schemas.datacontract.org/2004/07/LaptopService")]
    [System.SerializableAttribute()]
    public partial class SanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AnHienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayDangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SoLanMuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SoLanXemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TonKhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idHSXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AnHien {
            get {
                return this.AnHienField;
            }
            set {
                if ((this.AnHienField.Equals(value) != true)) {
                    this.AnHienField = value;
                    this.RaisePropertyChanged("AnHien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hinh {
            get {
                return this.HinhField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhField, value) != true)) {
                    this.HinhField = value;
                    this.RaisePropertyChanged("Hinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoTa {
            get {
                return this.MoTaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaField, value) != true)) {
                    this.MoTaField = value;
                    this.RaisePropertyChanged("MoTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayDang {
            get {
                return this.NgayDangField;
            }
            set {
                if ((this.NgayDangField.Equals(value) != true)) {
                    this.NgayDangField = value;
                    this.RaisePropertyChanged("NgayDang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SoLanMua {
            get {
                return this.SoLanMuaField;
            }
            set {
                if ((this.SoLanMuaField.Equals(value) != true)) {
                    this.SoLanMuaField = value;
                    this.RaisePropertyChanged("SoLanMua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SoLanXem {
            get {
                return this.SoLanXemField;
            }
            set {
                if ((this.SoLanXemField.Equals(value) != true)) {
                    this.SoLanXemField = value;
                    this.RaisePropertyChanged("SoLanXem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TonKho {
            get {
                return this.TonKhoField;
            }
            set {
                if ((this.TonKhoField.Equals(value) != true)) {
                    this.TonKhoField = value;
                    this.RaisePropertyChanged("TonKho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idHSX {
            get {
                return this.idHSXField;
            }
            set {
                if ((this.idHSXField.Equals(value) != true)) {
                    this.idHSXField = value;
                    this.RaisePropertyChanged("idHSX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idLoai {
            get {
                return this.idLoaiField;
            }
            set {
                if ((this.idLoaiField.Equals(value) != true)) {
                    this.idLoaiField = value;
                    this.RaisePropertyChanged("idLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSP {
            get {
                return this.idSPField;
            }
            set {
                if ((this.idSPField.Equals(value) != true)) {
                    this.idSPField = value;
                    this.RaisePropertyChanged("idSP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoaiSP", Namespace="http://schemas.datacontract.org/2004/07/LaptopService")]
    [System.SerializableAttribute()]
    public partial class LoaiSP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AnHienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ThuTuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idCLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idLoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AnHien {
            get {
                return this.AnHienField;
            }
            set {
                if ((this.AnHienField.Equals(value) != true)) {
                    this.AnHienField = value;
                    this.RaisePropertyChanged("AnHien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoai {
            get {
                return this.TenLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiField, value) != true)) {
                    this.TenLoaiField = value;
                    this.RaisePropertyChanged("TenLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ThuTu {
            get {
                return this.ThuTuField;
            }
            set {
                if ((this.ThuTuField.Equals(value) != true)) {
                    this.ThuTuField = value;
                    this.RaisePropertyChanged("ThuTu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCL {
            get {
                return this.idCLField;
            }
            set {
                if ((this.idCLField.Equals(value) != true)) {
                    this.idCLField = value;
                    this.RaisePropertyChanged("idCL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idLoai {
            get {
                return this.idLoaiField;
            }
            set {
                if ((this.idLoaiField.Equals(value) != true)) {
                    this.idLoaiField = value;
                    this.RaisePropertyChanged("idLoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonHang", Namespace="http://schemas.datacontract.org/2004/07/LaptopService")]
    [System.SerializableAttribute()]
    public partial class DonHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaDiemGiaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GhiChuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayGiaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNguoiNhanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ThoiGianDatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TinhTrangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> tongtienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaDiemGiao {
            get {
                return this.DiaDiemGiaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaDiemGiaoField, value) != true)) {
                    this.DiaDiemGiaoField = value;
                    this.RaisePropertyChanged("DiaDiemGiao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GhiChu {
            get {
                return this.GhiChuField;
            }
            set {
                if ((object.ReferenceEquals(this.GhiChuField, value) != true)) {
                    this.GhiChuField = value;
                    this.RaisePropertyChanged("GhiChu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayGiao {
            get {
                return this.NgayGiaoField;
            }
            set {
                if ((this.NgayGiaoField.Equals(value) != true)) {
                    this.NgayGiaoField = value;
                    this.RaisePropertyChanged("NgayGiao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNguoiNhan {
            get {
                return this.TenNguoiNhanField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNguoiNhanField, value) != true)) {
                    this.TenNguoiNhanField = value;
                    this.RaisePropertyChanged("TenNguoiNhan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ThoiGianDat {
            get {
                return this.ThoiGianDatField;
            }
            set {
                if ((this.ThoiGianDatField.Equals(value) != true)) {
                    this.ThoiGianDatField = value;
                    this.RaisePropertyChanged("ThoiGianDat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TinhTrang {
            get {
                return this.TinhTrangField;
            }
            set {
                if ((this.TinhTrangField.Equals(value) != true)) {
                    this.TinhTrangField = value;
                    this.RaisePropertyChanged("TinhTrang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDH {
            get {
                return this.idDHField;
            }
            set {
                if ((this.idDHField.Equals(value) != true)) {
                    this.idDHField = value;
                    this.RaisePropertyChanged("idDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idKH {
            get {
                return this.idKHField;
            }
            set {
                if ((this.idKHField.Equals(value) != true)) {
                    this.idKHField = value;
                    this.RaisePropertyChanged("idKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> tongtien {
            get {
                return this.tongtienField;
            }
            set {
                if ((this.tongtienField.Equals(value) != true)) {
                    this.tongtienField = value;
                    this.RaisePropertyChanged("tongtien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HangSanXuat", Namespace="http://schemas.datacontract.org/2004/07/LaptopService")]
    [System.SerializableAttribute()]
    public partial class HangSanXuat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AnHienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenHSXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idHSXField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AnHien {
            get {
                return this.AnHienField;
            }
            set {
                if ((this.AnHienField.Equals(value) != true)) {
                    this.AnHienField = value;
                    this.RaisePropertyChanged("AnHien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenHSX {
            get {
                return this.TenHSXField;
            }
            set {
                if ((object.ReferenceEquals(this.TenHSXField, value) != true)) {
                    this.TenHSXField = value;
                    this.RaisePropertyChanged("TenHSX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idHSX {
            get {
                return this.idHSXField;
            }
            set {
                if ((this.idHSXField.Equals(value) != true)) {
                    this.idHSXField = value;
                    this.RaisePropertyChanged("idHSX");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhachHang", Namespace="http://schemas.datacontract.org/2004/07/LaptopService")]
    [System.SerializableAttribute()]
    public partial class KhachHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KichHoatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayDKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idKHField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KichHoat {
            get {
                return this.KichHoatField;
            }
            set {
                if ((this.KichHoatField.Equals(value) != true)) {
                    this.KichHoatField = value;
                    this.RaisePropertyChanged("KichHoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayDK {
            get {
                return this.NgayDKField;
            }
            set {
                if ((this.NgayDKField.Equals(value) != true)) {
                    this.NgayDKField = value;
                    this.RaisePropertyChanged("NgayDK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idKH {
            get {
                return this.idKHField;
            }
            set {
                if ((this.idKHField.Equals(value) != true)) {
                    this.idKHField = value;
                    this.RaisePropertyChanged("idKH");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonHangChiTiet", Namespace="http://schemas.datacontract.org/2004/07/LaptopService")]
    [System.SerializableAttribute()]
    public partial class DonHangChiTiet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDH {
            get {
                return this.idDHField;
            }
            set {
                if ((this.idDHField.Equals(value) != true)) {
                    this.idDHField = value;
                    this.RaisePropertyChanged("idDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSP {
            get {
                return this.idSPField;
            }
            set {
                if ((this.idSPField.Equals(value) != true)) {
                    this.idSPField = value;
                    this.RaisePropertyChanged("idSP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChungLoai", Namespace="http://schemas.datacontract.org/2004/07/LaptopService")]
    [System.SerializableAttribute()]
    public partial class ChungLoai : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AnHienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenCLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ThuTuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AnHien {
            get {
                return this.AnHienField;
            }
            set {
                if ((this.AnHienField.Equals(value) != true)) {
                    this.AnHienField = value;
                    this.RaisePropertyChanged("AnHien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenCL {
            get {
                return this.TenCLField;
            }
            set {
                if ((object.ReferenceEquals(this.TenCLField, value) != true)) {
                    this.TenCLField = value;
                    this.RaisePropertyChanged("TenCL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ThuTu {
            get {
                return this.ThuTuField;
            }
            set {
                if ((this.ThuTuField.Equals(value) != true)) {
                    this.ThuTuField = value;
                    this.RaisePropertyChanged("ThuTu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCL {
            get {
                return this.idCLField;
            }
            set {
                if ((this.idCLField.Equals(value) != true)) {
                    this.idCLField = value;
                    this.RaisePropertyChanged("idCL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/LaptopService")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaiKhoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaiKhoan {
            get {
                return this.TaiKhoanField;
            }
            set {
                if ((object.ReferenceEquals(this.TaiKhoanField, value) != true)) {
                    this.TaiKhoanField = value;
                    this.RaisePropertyChanged("TaiKhoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPindex", ReplyAction="http://tempuri.org/IService1/LaySPindexResponse")]
        StoreLaptop.ServiceReference.SanPham[] LaySPindex();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPindex", ReplyAction="http://tempuri.org/IService1/LaySPindexResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPindexAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayLoaiSP", ReplyAction="http://tempuri.org/IService1/LayLoaiSPResponse")]
        StoreLaptop.ServiceReference.LoaiSP[] LayLoaiSP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayLoaiSP", ReplyAction="http://tempuri.org/IService1/LayLoaiSPResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.LoaiSP[]> LayLoaiSPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay1DH", ReplyAction="http://tempuri.org/IService1/Lay1DHResponse")]
        StoreLaptop.ServiceReference.DonHang[] Lay1DH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay1DH", ReplyAction="http://tempuri.org/IService1/Lay1DHResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.DonHang[]> Lay1DHAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPmoi", ReplyAction="http://tempuri.org/IService1/LaySPmoiResponse")]
        StoreLaptop.ServiceReference.SanPham[] LaySPmoi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPmoi", ReplyAction="http://tempuri.org/IService1/LaySPmoiResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPmoiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayHSX", ReplyAction="http://tempuri.org/IService1/LayHSXResponse")]
        StoreLaptop.ServiceReference.HangSanXuat[] LayHSX();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayHSX", ReplyAction="http://tempuri.org/IService1/LayHSXResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.HangSanXuat[]> LayHSXAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemtraHSX", ReplyAction="http://tempuri.org/IService1/KiemtraHSXResponse")]
        StoreLaptop.ServiceReference.HangSanXuat KiemtraHSX(int idHSX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemtraHSX", ReplyAction="http://tempuri.org/IService1/KiemtraHSXResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.HangSanXuat> KiemtraHSXAsync(int idHSX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPtheoHSX", ReplyAction="http://tempuri.org/IService1/LaySPtheoHSXResponse")]
        StoreLaptop.ServiceReference.SanPham[] LaySPtheoHSX(int idHSX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPtheoHSX", ReplyAction="http://tempuri.org/IService1/LaySPtheoHSXResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPtheoHSXAsync(int idHSX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChiTietSP", ReplyAction="http://tempuri.org/IService1/ChiTietSPResponse")]
        StoreLaptop.ServiceReference.SanPham ChiTietSP(int idSP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChiTietSP", ReplyAction="http://tempuri.org/IService1/ChiTietSPResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham> ChiTietSPAsync(int idSP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemKH", ReplyAction="http://tempuri.org/IService1/ThemKHResponse")]
        int ThemKH(StoreLaptop.ServiceReference.KhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemKH", ReplyAction="http://tempuri.org/IService1/ThemKHResponse")]
        System.Threading.Tasks.Task<int> ThemKHAsync(StoreLaptop.ServiceReference.KhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemDonHang", ReplyAction="http://tempuri.org/IService1/ThemDonHangResponse")]
        int ThemDonHang(StoreLaptop.ServiceReference.DonHang dh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemDonHang", ReplyAction="http://tempuri.org/IService1/ThemDonHangResponse")]
        System.Threading.Tasks.Task<int> ThemDonHangAsync(StoreLaptop.ServiceReference.DonHang dh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemTraTK", ReplyAction="http://tempuri.org/IService1/KiemTraTKResponse")]
        int KiemTraTK(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemTraTK", ReplyAction="http://tempuri.org/IService1/KiemTraTKResponse")]
        System.Threading.Tasks.Task<int> KiemTraTKAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KTDangNhap", ReplyAction="http://tempuri.org/IService1/KTDangNhapResponse")]
        StoreLaptop.ServiceReference.KhachHang KTDangNhap(string taikhoan, string matkhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KTDangNhap", ReplyAction="http://tempuri.org/IService1/KTDangNhapResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.KhachHang> KTDangNhapAsync(string taikhoan, string matkhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPcart", ReplyAction="http://tempuri.org/IService1/LaySPcartResponse")]
        StoreLaptop.ServiceReference.SanPham LaySPcart(int idSP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPcart", ReplyAction="http://tempuri.org/IService1/LaySPcartResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham> LaySPcartAsync(int idSP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPtheoid", ReplyAction="http://tempuri.org/IService1/LaySPtheoidResponse")]
        StoreLaptop.ServiceReference.SanPham LaySPtheoid(int sidSP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPtheoid", ReplyAction="http://tempuri.org/IService1/LaySPtheoidResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham> LaySPtheoidAsync(int sidSP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemCTDH", ReplyAction="http://tempuri.org/IService1/ThemCTDHResponse")]
        int ThemCTDH(StoreLaptop.ServiceReference.DonHangChiTiet ctdh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemCTDH", ReplyAction="http://tempuri.org/IService1/ThemCTDHResponse")]
        System.Threading.Tasks.Task<int> ThemCTDHAsync(StoreLaptop.ServiceReference.DonHangChiTiet ctdh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayChungLoai", ReplyAction="http://tempuri.org/IService1/LayChungLoaiResponse")]
        StoreLaptop.ServiceReference.ChungLoai[] LayChungLoai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayChungLoai", ReplyAction="http://tempuri.org/IService1/LayChungLoaiResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.ChungLoai[]> LayChungLoaiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KTLoaiSP", ReplyAction="http://tempuri.org/IService1/KTLoaiSPResponse")]
        StoreLaptop.ServiceReference.LoaiSP KTLoaiSP(int idLoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KTLoaiSP", ReplyAction="http://tempuri.org/IService1/KTLoaiSPResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.LoaiSP> KTLoaiSPAsync(int idLoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPtheoLoai", ReplyAction="http://tempuri.org/IService1/LaySPtheoLoaiResponse")]
        StoreLaptop.ServiceReference.SanPham[] LaySPtheoLoai(int idLoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPtheoLoai", ReplyAction="http://tempuri.org/IService1/LaySPtheoLoaiResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPtheoLoaiAsync(int idLoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPcungloai", ReplyAction="http://tempuri.org/IService1/LaySPcungloaiResponse")]
        StoreLaptop.ServiceReference.SanPham[] LaySPcungloai(int idLoai, int idSP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPcungloai", ReplyAction="http://tempuri.org/IService1/LaySPcungloaiResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPcungloaiAsync(int idLoai, int idSP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPHsx", ReplyAction="http://tempuri.org/IService1/LaySPHsxResponse")]
        StoreLaptop.ServiceReference.SanPham[] LaySPHsx(int idHSX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySPHsx", ReplyAction="http://tempuri.org/IService1/LaySPHsxResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPHsxAsync(int idHSX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySP", ReplyAction="http://tempuri.org/IService1/LaySPResponse")]
        StoreLaptop.ServiceReference.SanPham[] LaySP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaySP", ReplyAction="http://tempuri.org/IService1/LaySPResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayHangsx", ReplyAction="http://tempuri.org/IService1/LayHangsxResponse")]
        StoreLaptop.ServiceReference.HangSanXuat[] LayHangsx();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayHangsx", ReplyAction="http://tempuri.org/IService1/LayHangsxResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.HangSanXuat[]> LayHangsxAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemMoi", ReplyAction="http://tempuri.org/IService1/ThemMoiResponse")]
        int ThemMoi(StoreLaptop.ServiceReference.SanPham sanpham);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemMoi", ReplyAction="http://tempuri.org/IService1/ThemMoiResponse")]
        System.Threading.Tasks.Task<int> ThemMoiAsync(StoreLaptop.ServiceReference.SanPham sanpham);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sua", ReplyAction="http://tempuri.org/IService1/SuaResponse")]
        StoreLaptop.ServiceReference.SanPham Sua(int idSP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sua", ReplyAction="http://tempuri.org/IService1/SuaResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham> SuaAsync(int idSP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChinhSua", ReplyAction="http://tempuri.org/IService1/ChinhSuaResponse")]
        int ChinhSua(StoreLaptop.ServiceReference.SanPham sanpham);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChinhSua", ReplyAction="http://tempuri.org/IService1/ChinhSuaResponse")]
        System.Threading.Tasks.Task<int> ChinhSuaAsync(StoreLaptop.ServiceReference.SanPham sanpham);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDH", ReplyAction="http://tempuri.org/IService1/LayDHResponse")]
        StoreLaptop.ServiceReference.DonHang[] LayDH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDH", ReplyAction="http://tempuri.org/IService1/LayDHResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.DonHang[]> LayDHAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay", ReplyAction="http://tempuri.org/IService1/LayResponse")]
        StoreLaptop.ServiceReference.DonHang Lay(int idDH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay", ReplyAction="http://tempuri.org/IService1/LayResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.DonHang> LayAsync(int idDH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaTinhTrang", ReplyAction="http://tempuri.org/IService1/SuaTinhTrangResponse")]
        int SuaTinhTrang(StoreLaptop.ServiceReference.DonHang donhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaTinhTrang", ReplyAction="http://tempuri.org/IService1/SuaTinhTrangResponse")]
        System.Threading.Tasks.Task<int> SuaTinhTrangAsync(StoreLaptop.ServiceReference.DonHang donhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XuLy_DangNhap", ReplyAction="http://tempuri.org/IService1/XuLy_DangNhapResponse")]
        StoreLaptop.ServiceReference.Admin XuLy_DangNhap(string tk, string mk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XuLy_DangNhap", ReplyAction="http://tempuri.org/IService1/XuLy_DangNhapResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.Admin> XuLy_DangNhapAsync(string tk, string mk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayKH", ReplyAction="http://tempuri.org/IService1/LayKHResponse")]
        StoreLaptop.ServiceReference.KhachHang[] LayKH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayKH", ReplyAction="http://tempuri.org/IService1/LayKHResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.KhachHang[]> LayKHAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Duyet", ReplyAction="http://tempuri.org/IService1/DuyetResponse")]
        int Duyet(StoreLaptop.ServiceReference.KhachHang khachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Duyet", ReplyAction="http://tempuri.org/IService1/DuyetResponse")]
        System.Threading.Tasks.Task<int> DuyetAsync(StoreLaptop.ServiceReference.KhachHang khachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaKH", ReplyAction="http://tempuri.org/IService1/XoaKHResponse")]
        int XoaKH(StoreLaptop.ServiceReference.KhachHang khachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaKH", ReplyAction="http://tempuri.org/IService1/XoaKHResponse")]
        System.Threading.Tasks.Task<int> XoaKHAsync(StoreLaptop.ServiceReference.KhachHang khachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Timkiem", ReplyAction="http://tempuri.org/IService1/TimkiemResponse")]
        StoreLaptop.ServiceReference.SanPham[] Timkiem(string TuKhoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Timkiem", ReplyAction="http://tempuri.org/IService1/TimkiemResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> TimkiemAsync(string TuKhoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemHSX", ReplyAction="http://tempuri.org/IService1/ThemHSXResponse")]
        int ThemHSX(StoreLaptop.ServiceReference.HangSanXuat HSX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemHSX", ReplyAction="http://tempuri.org/IService1/ThemHSXResponse")]
        System.Threading.Tasks.Task<int> ThemHSXAsync(StoreLaptop.ServiceReference.HangSanXuat HSX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaHSX", ReplyAction="http://tempuri.org/IService1/SuaHSXResponse")]
        int SuaHSX(StoreLaptop.ServiceReference.HangSanXuat HSX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaHSX", ReplyAction="http://tempuri.org/IService1/SuaHSXResponse")]
        System.Threading.Tasks.Task<int> SuaHSXAsync(StoreLaptop.ServiceReference.HangSanXuat HSX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDHCT", ReplyAction="http://tempuri.org/IService1/LayDHCTResponse")]
        StoreLaptop.ServiceReference.DonHangChiTiet[] LayDHCT(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDHCT", ReplyAction="http://tempuri.org/IService1/LayDHCTResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.DonHangChiTiet[]> LayDHCTAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KTKH", ReplyAction="http://tempuri.org/IService1/KTKHResponse")]
        StoreLaptop.ServiceReference.KhachHang KTKH(int idKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KTKH", ReplyAction="http://tempuri.org/IService1/KTKHResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.KhachHang> KTKHAsync(int idKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoiMK", ReplyAction="http://tempuri.org/IService1/DoiMKResponse")]
        int DoiMK(StoreLaptop.ServiceReference.KhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoiMK", ReplyAction="http://tempuri.org/IService1/DoiMKResponse")]
        System.Threading.Tasks.Task<int> DoiMKAsync(StoreLaptop.ServiceReference.KhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay1KH", ReplyAction="http://tempuri.org/IService1/Lay1KHResponse")]
        StoreLaptop.ServiceReference.KhachHang Lay1KH(int idKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay1KH", ReplyAction="http://tempuri.org/IService1/Lay1KHResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.KhachHang> Lay1KHAsync(int idKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaKH", ReplyAction="http://tempuri.org/IService1/SuaKHResponse")]
        int SuaKH(StoreLaptop.ServiceReference.KhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaKH", ReplyAction="http://tempuri.org/IService1/SuaKHResponse")]
        System.Threading.Tasks.Task<int> SuaKHAsync(StoreLaptop.ServiceReference.KhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDHTheoKH", ReplyAction="http://tempuri.org/IService1/LayDHTheoKHResponse")]
        StoreLaptop.ServiceReference.DonHang[] LayDHTheoKH(int idKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDHTheoKH", ReplyAction="http://tempuri.org/IService1/LayDHTheoKHResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.DonHang[]> LayDHTheoKHAsync(int idKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatDonHang", ReplyAction="http://tempuri.org/IService1/CapNhatDonHangResponse")]
        StoreLaptop.ServiceReference.DonHang CapNhatDonHang(int idDH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatDonHang", ReplyAction="http://tempuri.org/IService1/CapNhatDonHangResponse")]
        System.Threading.Tasks.Task<StoreLaptop.ServiceReference.DonHang> CapNhatDonHangAsync(int idDH);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : StoreLaptop.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<StoreLaptop.ServiceReference.IService1>, StoreLaptop.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StoreLaptop.ServiceReference.SanPham[] LaySPindex() {
            return base.Channel.LaySPindex();
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPindexAsync() {
            return base.Channel.LaySPindexAsync();
        }
        
        public StoreLaptop.ServiceReference.LoaiSP[] LayLoaiSP() {
            return base.Channel.LayLoaiSP();
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.LoaiSP[]> LayLoaiSPAsync() {
            return base.Channel.LayLoaiSPAsync();
        }
        
        public StoreLaptop.ServiceReference.DonHang[] Lay1DH() {
            return base.Channel.Lay1DH();
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.DonHang[]> Lay1DHAsync() {
            return base.Channel.Lay1DHAsync();
        }
        
        public StoreLaptop.ServiceReference.SanPham[] LaySPmoi() {
            return base.Channel.LaySPmoi();
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPmoiAsync() {
            return base.Channel.LaySPmoiAsync();
        }
        
        public StoreLaptop.ServiceReference.HangSanXuat[] LayHSX() {
            return base.Channel.LayHSX();
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.HangSanXuat[]> LayHSXAsync() {
            return base.Channel.LayHSXAsync();
        }
        
        public StoreLaptop.ServiceReference.HangSanXuat KiemtraHSX(int idHSX) {
            return base.Channel.KiemtraHSX(idHSX);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.HangSanXuat> KiemtraHSXAsync(int idHSX) {
            return base.Channel.KiemtraHSXAsync(idHSX);
        }
        
        public StoreLaptop.ServiceReference.SanPham[] LaySPtheoHSX(int idHSX) {
            return base.Channel.LaySPtheoHSX(idHSX);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPtheoHSXAsync(int idHSX) {
            return base.Channel.LaySPtheoHSXAsync(idHSX);
        }
        
        public StoreLaptop.ServiceReference.SanPham ChiTietSP(int idSP) {
            return base.Channel.ChiTietSP(idSP);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham> ChiTietSPAsync(int idSP) {
            return base.Channel.ChiTietSPAsync(idSP);
        }
        
        public int ThemKH(StoreLaptop.ServiceReference.KhachHang kh) {
            return base.Channel.ThemKH(kh);
        }
        
        public System.Threading.Tasks.Task<int> ThemKHAsync(StoreLaptop.ServiceReference.KhachHang kh) {
            return base.Channel.ThemKHAsync(kh);
        }
        
        public int ThemDonHang(StoreLaptop.ServiceReference.DonHang dh) {
            return base.Channel.ThemDonHang(dh);
        }
        
        public System.Threading.Tasks.Task<int> ThemDonHangAsync(StoreLaptop.ServiceReference.DonHang dh) {
            return base.Channel.ThemDonHangAsync(dh);
        }
        
        public int KiemTraTK(string Email) {
            return base.Channel.KiemTraTK(Email);
        }
        
        public System.Threading.Tasks.Task<int> KiemTraTKAsync(string Email) {
            return base.Channel.KiemTraTKAsync(Email);
        }
        
        public StoreLaptop.ServiceReference.KhachHang KTDangNhap(string taikhoan, string matkhau) {
            return base.Channel.KTDangNhap(taikhoan, matkhau);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.KhachHang> KTDangNhapAsync(string taikhoan, string matkhau) {
            return base.Channel.KTDangNhapAsync(taikhoan, matkhau);
        }
        
        public StoreLaptop.ServiceReference.SanPham LaySPcart(int idSP) {
            return base.Channel.LaySPcart(idSP);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham> LaySPcartAsync(int idSP) {
            return base.Channel.LaySPcartAsync(idSP);
        }
        
        public StoreLaptop.ServiceReference.SanPham LaySPtheoid(int sidSP) {
            return base.Channel.LaySPtheoid(sidSP);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham> LaySPtheoidAsync(int sidSP) {
            return base.Channel.LaySPtheoidAsync(sidSP);
        }
        
        public int ThemCTDH(StoreLaptop.ServiceReference.DonHangChiTiet ctdh) {
            return base.Channel.ThemCTDH(ctdh);
        }
        
        public System.Threading.Tasks.Task<int> ThemCTDHAsync(StoreLaptop.ServiceReference.DonHangChiTiet ctdh) {
            return base.Channel.ThemCTDHAsync(ctdh);
        }
        
        public StoreLaptop.ServiceReference.ChungLoai[] LayChungLoai() {
            return base.Channel.LayChungLoai();
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.ChungLoai[]> LayChungLoaiAsync() {
            return base.Channel.LayChungLoaiAsync();
        }
        
        public StoreLaptop.ServiceReference.LoaiSP KTLoaiSP(int idLoai) {
            return base.Channel.KTLoaiSP(idLoai);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.LoaiSP> KTLoaiSPAsync(int idLoai) {
            return base.Channel.KTLoaiSPAsync(idLoai);
        }
        
        public StoreLaptop.ServiceReference.SanPham[] LaySPtheoLoai(int idLoai) {
            return base.Channel.LaySPtheoLoai(idLoai);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPtheoLoaiAsync(int idLoai) {
            return base.Channel.LaySPtheoLoaiAsync(idLoai);
        }
        
        public StoreLaptop.ServiceReference.SanPham[] LaySPcungloai(int idLoai, int idSP) {
            return base.Channel.LaySPcungloai(idLoai, idSP);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPcungloaiAsync(int idLoai, int idSP) {
            return base.Channel.LaySPcungloaiAsync(idLoai, idSP);
        }
        
        public StoreLaptop.ServiceReference.SanPham[] LaySPHsx(int idHSX) {
            return base.Channel.LaySPHsx(idHSX);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPHsxAsync(int idHSX) {
            return base.Channel.LaySPHsxAsync(idHSX);
        }
        
        public StoreLaptop.ServiceReference.SanPham[] LaySP() {
            return base.Channel.LaySP();
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> LaySPAsync() {
            return base.Channel.LaySPAsync();
        }
        
        public StoreLaptop.ServiceReference.HangSanXuat[] LayHangsx() {
            return base.Channel.LayHangsx();
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.HangSanXuat[]> LayHangsxAsync() {
            return base.Channel.LayHangsxAsync();
        }
        
        public int ThemMoi(StoreLaptop.ServiceReference.SanPham sanpham) {
            return base.Channel.ThemMoi(sanpham);
        }
        
        public System.Threading.Tasks.Task<int> ThemMoiAsync(StoreLaptop.ServiceReference.SanPham sanpham) {
            return base.Channel.ThemMoiAsync(sanpham);
        }
        
        public StoreLaptop.ServiceReference.SanPham Sua(int idSP) {
            return base.Channel.Sua(idSP);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham> SuaAsync(int idSP) {
            return base.Channel.SuaAsync(idSP);
        }
        
        public int ChinhSua(StoreLaptop.ServiceReference.SanPham sanpham) {
            return base.Channel.ChinhSua(sanpham);
        }
        
        public System.Threading.Tasks.Task<int> ChinhSuaAsync(StoreLaptop.ServiceReference.SanPham sanpham) {
            return base.Channel.ChinhSuaAsync(sanpham);
        }
        
        public StoreLaptop.ServiceReference.DonHang[] LayDH() {
            return base.Channel.LayDH();
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.DonHang[]> LayDHAsync() {
            return base.Channel.LayDHAsync();
        }
        
        public StoreLaptop.ServiceReference.DonHang Lay(int idDH) {
            return base.Channel.Lay(idDH);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.DonHang> LayAsync(int idDH) {
            return base.Channel.LayAsync(idDH);
        }
        
        public int SuaTinhTrang(StoreLaptop.ServiceReference.DonHang donhang) {
            return base.Channel.SuaTinhTrang(donhang);
        }
        
        public System.Threading.Tasks.Task<int> SuaTinhTrangAsync(StoreLaptop.ServiceReference.DonHang donhang) {
            return base.Channel.SuaTinhTrangAsync(donhang);
        }
        
        public StoreLaptop.ServiceReference.Admin XuLy_DangNhap(string tk, string mk) {
            return base.Channel.XuLy_DangNhap(tk, mk);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.Admin> XuLy_DangNhapAsync(string tk, string mk) {
            return base.Channel.XuLy_DangNhapAsync(tk, mk);
        }
        
        public StoreLaptop.ServiceReference.KhachHang[] LayKH() {
            return base.Channel.LayKH();
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.KhachHang[]> LayKHAsync() {
            return base.Channel.LayKHAsync();
        }
        
        public int Duyet(StoreLaptop.ServiceReference.KhachHang khachhang) {
            return base.Channel.Duyet(khachhang);
        }
        
        public System.Threading.Tasks.Task<int> DuyetAsync(StoreLaptop.ServiceReference.KhachHang khachhang) {
            return base.Channel.DuyetAsync(khachhang);
        }
        
        public int XoaKH(StoreLaptop.ServiceReference.KhachHang khachhang) {
            return base.Channel.XoaKH(khachhang);
        }
        
        public System.Threading.Tasks.Task<int> XoaKHAsync(StoreLaptop.ServiceReference.KhachHang khachhang) {
            return base.Channel.XoaKHAsync(khachhang);
        }
        
        public StoreLaptop.ServiceReference.SanPham[] Timkiem(string TuKhoa) {
            return base.Channel.Timkiem(TuKhoa);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.SanPham[]> TimkiemAsync(string TuKhoa) {
            return base.Channel.TimkiemAsync(TuKhoa);
        }
        
        public int ThemHSX(StoreLaptop.ServiceReference.HangSanXuat HSX) {
            return base.Channel.ThemHSX(HSX);
        }
        
        public System.Threading.Tasks.Task<int> ThemHSXAsync(StoreLaptop.ServiceReference.HangSanXuat HSX) {
            return base.Channel.ThemHSXAsync(HSX);
        }
        
        public int SuaHSX(StoreLaptop.ServiceReference.HangSanXuat HSX) {
            return base.Channel.SuaHSX(HSX);
        }
        
        public System.Threading.Tasks.Task<int> SuaHSXAsync(StoreLaptop.ServiceReference.HangSanXuat HSX) {
            return base.Channel.SuaHSXAsync(HSX);
        }
        
        public StoreLaptop.ServiceReference.DonHangChiTiet[] LayDHCT(int id) {
            return base.Channel.LayDHCT(id);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.DonHangChiTiet[]> LayDHCTAsync(int id) {
            return base.Channel.LayDHCTAsync(id);
        }
        
        public StoreLaptop.ServiceReference.KhachHang KTKH(int idKH) {
            return base.Channel.KTKH(idKH);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.KhachHang> KTKHAsync(int idKH) {
            return base.Channel.KTKHAsync(idKH);
        }
        
        public int DoiMK(StoreLaptop.ServiceReference.KhachHang kh) {
            return base.Channel.DoiMK(kh);
        }
        
        public System.Threading.Tasks.Task<int> DoiMKAsync(StoreLaptop.ServiceReference.KhachHang kh) {
            return base.Channel.DoiMKAsync(kh);
        }
        
        public StoreLaptop.ServiceReference.KhachHang Lay1KH(int idKH) {
            return base.Channel.Lay1KH(idKH);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.KhachHang> Lay1KHAsync(int idKH) {
            return base.Channel.Lay1KHAsync(idKH);
        }
        
        public int SuaKH(StoreLaptop.ServiceReference.KhachHang kh) {
            return base.Channel.SuaKH(kh);
        }
        
        public System.Threading.Tasks.Task<int> SuaKHAsync(StoreLaptop.ServiceReference.KhachHang kh) {
            return base.Channel.SuaKHAsync(kh);
        }
        
        public StoreLaptop.ServiceReference.DonHang[] LayDHTheoKH(int idKH) {
            return base.Channel.LayDHTheoKH(idKH);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.DonHang[]> LayDHTheoKHAsync(int idKH) {
            return base.Channel.LayDHTheoKHAsync(idKH);
        }
        
        public StoreLaptop.ServiceReference.DonHang CapNhatDonHang(int idDH) {
            return base.Channel.CapNhatDonHang(idDH);
        }
        
        public System.Threading.Tasks.Task<StoreLaptop.ServiceReference.DonHang> CapNhatDonHangAsync(int idDH) {
            return base.Channel.CapNhatDonHangAsync(idDH);
        }
    }
}
